#! /bin/bash

EMBED=false
render_args=()

# Parse arguments: consume --embed here, forward the rest to images/render.sh
while [[ $# -gt 0 ]]; do
	case $1 in
		--embed)
			EMBED=true
			shift
			;;
		*)
			render_args+=("$1")
			shift
			;;
	esac
done

pushd images
./render "${render_args[@]}"
popd

# Auto-discover all .bib files and create bibliography arguments
bib_args=""
for bibfile in *.bib; do
    if [ -f "$bibfile" ]; then
        bib_args="$bib_args --bibliography=$bibfile"
    fi
done

embed_flag=""
if $EMBED; then
	embed_flag="--embed-resources"
fi

pandoc -s --mathml -i -t revealjs $embed_flag --standalone --citeproc $bib_args --csl=/usr/share/texlive/texmf-dist/tex/latex/citation-style-language/styles/ieee.csl presentation.md -o presentation.html
